### ISSUE TITLE
Self Reset to default value on QlikSense Server (via Browser)

### ISSUE THREAD

**Issue by meeno82** [AssureeServices/MULTIPLE-BUTTONS#1]
It works perfectly on QlikSense Desktop. On the other hand, QlikServer side, It self-reset to the default selection of the multiple button switch after few seconds, while navigating the app via browser.

Someone has the same trouble or knows how to fix it?

Thx,
Claudio

**Comment by hnguyen515A** [comment]
I have the same issue. When linking from a sheet to another sheet that has the extension on it the selection made from the originating sheet was wiped out on the targeting sheet. Not sure what to do because this extension is perfect for what we need. I'll probably find another workaround without using the extension.
Thanks,
H Nguyen

**Comment by alexcolo** [comment]
Claudio i have the same issue. It self-reset to the deafult selection only after the app is published. When the app is not published the extension works perfectly.
Any news on that?

Thanks
Alex

**Comment by deviraLSA** [comment]
Hi,

I have the same issue. It self-reset to the default selection after few second when using the app via browser.
Is there any way to fix it? or any workaround? 

Thanks,
Devira

**Comment by deviraLSA** [comment]
Hi @meeno82 @hnguyen515A @alexcolo @AssureeServices 

I have the same issue. It self-reset to the default selection after few second when using the app via browser.
Is there any way to fix it? or any workaround?

Thanks,
Devira

**Comment by AssureeServices** [comment]
Hi,

    You can't use this extension more than one time in a same sheet but you can use more than one time in an application.

    You must save the application on every selection/changing the value in Multiple Button extension.

    If you did not save the application it will automatically select the default value/previous selection.

    I have created an application in my local Qlik Desktop then published in QMC. I also checked the issue once again but it's working fine without any issues.  

  My Version info is listed below

	Qlik Sense 3.2 SR4
	Qlik Sense Server 10.28.2 

Thanks,
Irfan K
